### ISSUE TITLE
BEP board might be required for VE9 XDclear OS upgrade

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#16]
Need to add pop up that warns of BEP6 requirement for VE9 OS upgrade. 

Also need to add BEP6 upgrade into SWB Where??

is BEP6 upgrade on PCM?

**Comment by svaughn3** [comment]
@dlabott 
opps forgot.

**Comment by svaughn3** [comment]
@dlabott 

H45581NC Bep 5 to BEP6 board. needs to be added to VE9 upgrade offering? along with pop up message.

**Comment by svaughn3** [comment]
@dlabott 
See email from Denise to Steve: 
Thu 1/25/2018 1:22 PM

**Comment by svaughn3** [comment]
@dlabott 
email Feb 28 to Denise with add instructions
add H45581NC and H45581NT to VE 9 Upgrade offering. 

description for H45581NT in for approval.

**Comment by dlabott** [comment]
@svaughn3 
OCR spreadsheet created 2 Mar 2018 with Steve.
ACTION: Denise to start Pega to add H45581NC to VIVID E9 BT11 AND BT12 AND XDCLEAR IB on 5 Mar 2018
description for H45581NC in DOC1709067
description for H45581NT in DOC1839684
Steve will stop approval for new DOC2106611

**Comment by svaughn3** [comment]
@dlabott 
May 2, 2018
found a problem with H45581NC. Price in SWB is $0. Not sure where I missed that. 

Price should be $5000.

**Comment by svaughn3** [comment]
@dlabott 
May 3, 2018
Denise loaded $5000 price into PET. 
should be in SWB on Friday. 
will close when in SWB. 
Steve will check and  close on Friday.

**Comment by svaughn3** [comment]
@dlabott 
May 4, 2018

checked SWB, price is showing correctly. 
closing this issue
