### ISSUE TITLE
1. R2.1 SWB offerings 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#18]
@svaughn3 

Add R2.1 to the existing offering in SWB. 
Same PCM - yes  VIVID-E-V202PCM
1. export existing offering. VE95 v202, VE90 v202, VE90 VE95 v202 Upgrades, VS60N v202, VS70N v202, 
       (Denise working on exports 5 Dec 2017)
Stay with old offering names except for: 
Vivid S60N S70N v202 Upgrades
PSI codes: 
Get new PSI codes for VE90/95 v202 R2_1 Upgrade hcat (H45591HT) and VS60N/S70N R2_1 hcat (H45591ZR) 
# **#PSI update: new OFC for the console, open issue on the PSI go forward plan - schedule skype with Bruce, Becky, Denise, Steve. Action: Steve**  
2. Send new hcats (marginator format) to denise - action steve (Done 5 Dec 2017)
3. deleted 
4. Make new offering - denise (Step 1 of 2 completed 5 Dec 2017)
5. add new hcats - Denise to add, Steve to review once in PEGA, if changes, resave to PEGA  (Denise working on adding hcats on 5, 6, 7 Dec 2017)
6. Approve PEGA. 
7. place offerings into NPI. Can be W49 or 50. 
8. NPI to CVUS in late Jan (W05). 

Critical path... 
descriptions  in for approval as of Monday dec 4. 
OFC

**Comment by svaughn3** [comment]
@dlabott

**Comment by svaughn3** [comment]
@dlabott 
Sending #2 above marginator input to Denise via email.

**Comment by dlabott** [comment]
@svaughn3 @dlabott I edited the initial posting with dates of my actual and expected progress. commenting here as I didn't receive a notification of my updates via email.

**Comment by dlabott** [comment]
@svaughn3 
#1 OCR-423  SWB_CPQ_7142 Vivid E90 VE95 v202 Upgrades pending RMM Assessment and Approval

**Comment by dlabott** [comment]
@svaughn3 

Denise sent Steve an email with screen shots and PSI offering status tracker spreadsheet.

Priority 1 – pending DGL change in SWB after 2 January
Priorities 2-3 – pending SV approval in Pega (OCR-428 & OCR-429)
Priority 4 – pending confirmation from SV if USOTH is ok for PSI
Priorities 4-7 – pending follow up on items missing from PCM and traceability of OFC from Joana (+ activation of OFC).

**Comment by svaughn3** [comment]
@dlabott 

Jan 1, 2018 
Priority 2, 3: approved with changes. revised files uploaded to pega.

**Comment by dlabott** [comment]
@svaughn3 
Priority 1 - VE90/95 Upgrades R2.1 offering
Denise to follow up with Ana (cc: Steve & Fansler) on final answer on PSI code in SFDC - change from UVI90D to UVI90G?
Question: when will new SW HCATs be available (ship dates)?
       Denise to update offering OCR-423 once ship dates are confirmed.

**Comment by dlabott** [comment]
@svaughn3 
Priorities 4-7 pending adding H45591PY 10T-D Enable S-series to VIVID-E-V202PCM.
Steve sending follow up email to make center (Joana V)

**Comment by dlabott** [comment]
@svaughn3 
Priorities 1-3 pushed to production.
Priorities 4-7 pending adding H45591PY 10T-D Enable S-series to VIVID-E-V202PCM

**Comment by svaughn3** [comment]
@dlabott 

10-T probe will not be compatible with the VS60N. 
Descriptions need to be updated (approved version for VS60N and VS70N v202 R2.1
Any other documentation wrong? 
Steve to check.

**Comment by svaughn3** [comment]
@dlabott 
May 1, 2018
OCR 436 is the PEGA for the S70N for USA  
OCR 430 is S70N upgrade offering. 
OCR 431 is PEGA for S70N 10T probe OFC. 
Not doing OCR 432 for VS60, as 10T not compatible with VS60 per MCR . 
Steve to revise and submit descriptions to remove VS60N language across all hcats - PD and OY
Discussing S70 situation with Joanna on May 2.

**Comment by svaughn3** [comment]
@dlabott 
May 3, 2018
Closing this item and opening separate one for the remaining VS70 tasks.
