### ISSUE TITLE
Remove TEE probe adapter from SWB H45541PX

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#21]
@dlabott 

We only have 2 remaining in stock and make center has notified us of end of life - no more orders. 

Denise if you can move on this without more input from me... please do. 

1. Which offerings are impacted? Please let me know. 
2. hold on the removal until I review 1 above. 

thanks

**Comment by dlabott** [comment]
@svaughn3 
On 7 offerings. 
Removing from SWB per discussion with Steve.
DGL end date for 7 Feb 2018.
3 quotes (email to Steve).

**Comment by svaughn3** [comment]
@dlabott 
Denise we have 2 in inventory and can probably sell them. 
Please end date March 2 instead of Feb 7

thanks

**Comment by dlabott** [comment]
@svaughn3 
H45541PX end dated for 3 Mar 2018.
Should disappear from SWB by 5 Mar 2018
7 Offerings. DGL emailed list to SV on 8 Feb 2018..
