### ISSUE TITLE
add warning about Vivid iq DVD mount HW 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#24]
@dlabott 

In the following offerings: 
Viq v202
Viq Premium v202
Viq 4D v202
Viq Premium v202 USA
Viq 4D v202 USA
Viq USA (Limited U/S Inventory)
Viq Premium USA (LUI)
Viq 4D USA (LUI)

Add Pop up for hcat: H48532LJ (DVD) 

Pop up should read:
No mounting hardware supplied with DVD. DVD can be mounted with printer mounting hardware supplied with H48942AW or H48952AF, purchased in conjunction with the Viq cart. 

Denise - can you go forward with adding this note?

**Comment by dlabott** [comment]
@svaughn3 
Completed 31 Jan 2018.
Should appear in SWB tomorrow.

**Comment by svaughn3** [comment]
Woot! Woot!

Bet that felt good!


Steve Vaughn

Cardiovascular Ultrasound
Regional Product Manager
Cardiovascular Ultrasound
GE Healthcare

M:+1 262 951 1734
E: steven.vaughn@ge.com<mailto:steven.vaughn@ge.com>

9900 Innovation Drive
RP-2121
Wauwatosa, WI 53226
USA
