### ISSUE TITLE
Remove TEE Cleaning and Storage Systemn H45551NK from SWB

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#25]
@dlabott 
Denise - I would like to have a GitHub instance for this issue. 

My SWB inquiry shows that this part is in 14 offerings.

**Comment by svaughn3** [comment]
@dlabott 
email to Denise requesting end date no later then Feb 23.

**Comment by dlabott** [comment]
@svaughn3 
Completed 23 Feb 2018.
