### ISSUE TITLE
Remove Vivid T8 R2 from SWB

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#26]
@dlabott 

Denise - would like to have a GitHub on this one. 

the T8 is in US Limited but console still in the offering, would like to remove console. 

Can you run a report on outstanding quotes? 

thanks

**Comment by svaughn3** [comment]
@dlabott 
email to Ana for any reason not to remove immediately.

**Comment by svaughn3** [comment]
@dlabott 
reply from Ana: 2 demo units to sell at AMB.
Denise - can we pull the "New" offering from SWB and leave the "Demo" offering? 

if yes, please move forward with pulling "New" from SWB.
Request end date for SWB of Feb 23.

**Comment by svaughn3** [comment]
@dlabott 
Feb 22: Denise removed Vscan quick buy and added the Demo console selection back into swb. 
New is removed also.

**Comment by dlabott** [comment]
@svaughn3 
Confirmed actions completed. Closing this action.
