### ISSUE TITLE
HCAT required for Digital Expert product (service product) 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#27]
@dlabott 

Need to set up hcat for Digital Expert and put into NPI (?)/ set up for "approval required". 
Probably won't go into NPI because it is needed for all Vivid products. 
I'll work with Aaron Hart, et al for description, pricing.

Very high priority. 
We'll need to set up an hcat for this service and training offering.

**Comment by svaughn3** [comment]
@dlabott 
Feb 22 update: 

Aaron Hart is pursuing RCAT with NAKASHIMA, YASUSHI (GE Healthcare) <yasushi.nakashima@ge.com> 

Hey Kevin,

Hoping you may be able to help…looking to get a part created for education which will be quoted and sold @ POS with equipment in the US. Here are the details…
-	It will be for education services
-	Revenue for the part needs to flow to ultrasound services in the US, seems the MCC should be 0483
-	We have a completed description etc. which I can provide if/when needed

Do you know who could help with this?

**Comment by svaughn3** [comment]
@dlabott 
Feb 22 email: 
Aaron answers that MCC is 483

**Comment by svaughn3** [comment]
@dlabott 
hcat is R0001DE
testing completed, worked as expected. 
first quotes NL. 
to do: 
1. Sent email to Aaron today (March 22), pending response.
2. will need pega for each offering. 
3. Set discounts for each offering. 
4. need export for each offering. put into Education and Training option class .. Applications nested class. 
5. or maybe put the Ultrasound Applications Training offering into CVUS (out of Ultrasound limited)

**Comment by svaughn3** [comment]
@dlabott 
April 4, 2018
approved description: DOC2104265

1.Sent email to Aaron today (March 22), pending response. **Done: Description doc identified**
2.will need pega for each offering.
3.Set discounts for each offering. **R0001DE should be non-discountable.** 
4.need export for each offering. put into Education and Training option class .. Applications nested class.  **I will do one "export" using SWB Master with placement of Rcat, rules, etc. (VE95) 
Denise - can you do VE90, VS70N, VS60N, Viq, Viq Premium, Viq 4D, Vivid T8 along with corresponding "for USA" offerings?** 
5.or maybe put the Ultrasound Applications Training offering into CVUS (out of Ultrasound limited) **Discussed with Aaron - don't go this way at this time.**

**Comment by svaughn3** [comment]
@dlabott 
Denise - not sure the above comment came through correctly. Please take a look at it. 
I will sent the VE95 example via email now. 

Let me know what you think. 
thanks

**Comment by svaughn3** [comment]
@dlabott 

April 4, 2018

Denise - I would like to get Digital Expert into one offering as quickly as we can. 
to the end... can you go ahead and put it into VE95 before going forward with the other products?

**Comment by dlabott** [comment]
@svaughn3 
Reposting 4 April comment AND adding update 6 April.
@dlabott
April 4, 2018
approved description: DOC2104265

1.Sent email to Aaron today (March 22), pending response. Done: Description doc identified
2.will need pega for each offering.
3.Set discounts for each offering. R0001DE should be non-discountable.
4.need export for each offering. put into Education and Training option class .. Applications nested class. I will do one "export" using SWB Master with placement of Rcat, rules, etc. (VE95)
Denise - can you do VE90, VS70N, VS60N, Viq, Viq Premium, Viq 4D, Vivid T8 along with corresponding "for USA" offerings?
5.or maybe put the Ultrasound Applications Training offering into CVUS (out of Ultrasound limited) Discussed with Aaron - don't go this way at this time.

UPDATE 6 April 2018:
Pending PC Ready Report status (Red).
DGL sent email to Petra to learn how to resolve. cc: Steve.
VE95 export/Pega created OCR-522 for Horten products. 
Pending answer before processing VE90, VS70N, VS60N, Viq, Viq Premium, Viq 4D, Vivid T8 + USA offerings.

**Comment by svaughn3** [comment]
@dlabott 

Any status update on this one?

**Comment by dlabott** [comment]
@svaughn3 
Denise sent update (from Petra) to Steve via email.

**Comment by svaughn3** [comment]
@dlabott 
april 12, 2018
proposal is to have service create new Rcat with the Non inventory type instead of "invoice only". 
steve to send email to denise for proofing and then to service group. 
steve send to service.

**Comment by dlabott** [comment]
@svaughn3 
Closing this case. Actions completed.
