### ISSUE TITLE
Remove any access to Advanced Contrast

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#33]
Scrub all offerings for advanced contrast. 

REmove if found.

**Comment by svaughn3** [comment]
@dlabott 
April 24

This is a hot one. 
I need to remove all instances of H45571GY in SWB. 
GoldSeal and Ultrasound Limited Inventory included. 

thanks

**Comment by dlabott** [comment]
@svaughn3 
Removed from SWB. Should disappear by tomorrow.
Chris Shireman has action to confirm when he removed from AMB/GoldSeal.
OK to close?

**Comment by dlabott** [comment]
@svaughn3 
DGL sent confirmation email to SV. 
Closing action.
