### ISSUE TITLE
GRLY bd out of VE90 VE95 collectors. 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#35]
Need to pull H45591KD GRLY Board out of VE90 VE95 upgrade offering collectors. 

H45591KJ VE90 v201 to v202 R2.1 Upgrade Package

H45591KH VE95 v201 to v202 R2.1 Upgrade Package

This  has a very high priority. 

See email for additional details.

**Comment by svaughn3** [comment]
@dlabott 

forgot to send copy to you.

**Comment by dlabott** [comment]
@svaughn3 
approved commercial change workflow Request ID : 177934462  29 Mar 2018
ACTION: STEVE description pending route in MWS for RA approval

**Comment by svaughn3** [comment]
@dlabott 

ECO is implemented. 
Steve is submitted revised description for approval.

**Comment by svaughn3** [comment]
@dlabott 

There are popups in SWB that require revision. They state that the GRLY bd should be ordered in various situations, but we need to open it up to the possibility of field upgrade only. 

Suggested wording: 

“An updated GRLY Bd is required for this functionality (or option) and may already be present. Work with your Service Engineer to determine if the GRLY Bd needs to be upgraded for your situation and how the upgrade will be installed.”

In discussion with Sales Ops and Engineering. 

Steve

**Comment by svaughn3** [comment]
@dlabott 
approved description revision has been emailed to Denise for implementation into SWB.

**Comment by dlabott** [comment]
@svaughn3 
Descriptions on H45591KJ and H45591KH updated 12 Apr 2018.
Should appear in SWB by Monday 16 Apr if the overnight production pushes process as expected.
