### ISSUE TITLE
Revise description for TEE rack

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#36]
@dlabott 

March 30: 

On Mar 30, 2018, at 2:44 AM, Lie, Glenn Reidar (GE Healthcare) <GlennReidar.Lie@ge.com> wrote:
Changing is easy. This is something that Steve can do with a product manager blessing. 
Glenn Reidar Lie

**Comment by svaughn3** [comment]
@dlabott 
April 25, 2018
Revised description is now approved. 
DOC2125394

Please proceed with updating description in SWB. 
Thanks

**Comment by dlabott** [comment]
@svaughn3 
Completed. Sent email to Steve.
