### ISSUE TITLE
Digital Expert into VE90 offering. 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#46]
@dlabott 
May 21, 2018

Add DE and add QB to VE90

**Comment by dlabott** [comment]
@svaughn3 
Please review and approve Pega OCR-558 Vivid E90 add R0001DE Digital Expert.
CPQ_7144 for E90
R0001DE is NON-DISCOUNTABLE!

**Comment by svaughn3** [comment]
@dlabott 
June 14, 2018

DE has been added to VE90 offering as non discountable. 
QB added today, should show in swb by Friday/Monday.
