### ISSUE TITLE
Remove H45021BB Battery from Vi and Vq offerings

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#52]
@dlabott 
June 19, 2018

Remove H45021BB Battery from Vi and Vq offerings. 
No longer available, cannot fulfill. 

from my check, 21BB appears in only one offering: Vivid i and Vivid q BT12 Only IB

**Comment by dlabott** [comment]
@svaughn3 
21 Jun 2018
Vivid i and Vivid q BT12 Only IB
SWB_CPQ_6704
DGL end dated H45021BB Secondary Scanning Battery on 23 Jun 2018.
Should disappear from SWB by Monday 25 Jun 2018

Check on Monday and close this case???

**Comment by svaughn3** [comment]
@dlabott 
June 28, 2018

Steve checked SWB - no H45021BB shows - good to close.
