### ISSUE TITLE
Add Isolated HDMI splitter H48982AN to VS70N offering

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#56]
@dlabott 
June 27, 2018
1. Add to offering
2. add to material plan
3. add to BWI contract pricing. 

Question out to HJG to understand why it was not in v202 pricelist. 
I have checked hcat in MWS and it shows used on appropriate PCMs.

**Comment by svaughn3** [comment]
@dlabott 
July 27, 2018

Denise can you take action on adding H48982AN to these offerings: 
VIVID S70N V202
VIVID S70N V202 FOR USA

Let me know if you need additional info from me. 

thank you

**Comment by dlabott** [comment]
@svaughn3 
August 8, 2018
OCR-601 in process.

**Comment by svaughn3** [comment]
@dlabott
 Aug 16, 2018

Denise added to SWB on Monday Aug 13.

should be active..

Steve will check in SWB. for closure.

**Comment by svaughn3** [comment]
@dlabott 
Aug 16, 2018

Steve checked VS70N and VS70N for USA offerings. 
VIVID S70N V202
 VIVID S70N V202 FOR USA
H48982AN is in both, but price in listed as "INCL". 

price should be $2500.

**Comment by dlabott** [comment]
@svaughn3 
August 16, 2018
List Price master updated via PDT Maintenance Workflow:
Please change list price on H48982AN HDMI splitter  from 1500 to 2500 in US$ in AM region per Region Marketing Manager Steve Vaughn.
Thank you.

PET updated to include correct list price.
Should appear in SWB tomorrow if the overnight production push processes as expected.

Steve to review and close on Friday 17 August 2018.

**Comment by svaughn3** [comment]
@dlabott 
Aug 23, 2018
Steve checked SWB for $2500 price - OK 

Closing!
