### ISSUE TITLE
Add 10T-D User Manual to VE90 VE95 VS70N 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#58]
@dlabott 
July 5, 2018
Add H45601FB to the offerings that have the 10T-D probe. VE90 VE95 VS70N

This manual was not in original release docs and was added later.

**Comment by svaughn3** [comment]
@dlabott 
July 27, 2018

Can you go forward with adding H45601FB 10T User Manual to the following offerings (in the Manuals and Documentation section): 

VIVID E90 V202
VIVID E95 V202
VIVID S70N V202
VIVID S70N V202 FOR USA

let me know if you need info from me. 

thanks

**Comment by svaughn3** [comment]
@dlabott 
Aug 6, 2018
need to add H45601FB to material plan or ensure that it is in material plan for R3

**Comment by dlabott** [comment]
@svaughn3 
August 8, 2018
OCR-601 in process.

**Comment by svaughn3** [comment]
@dlabott 
Aug 16, 2018

Denise added to SWB on Monday Aug 13. 

should be active.. 

Steve will check in SWB. for closure.

**Comment by svaughn3** [comment]
@dlabott 
Aug 16, 2018

Closed!

**Comment by svaughn3** [comment]
@dlabott
 Aug 16, 2018

Closed!
