### ISSUE TITLE
ICE into VS70N

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#6]
Tasks:

1. Pull Export of VS70N and VS70N for USA offering. 
2. Add ICE SW, ICE Probe, Carto options, video options. . also account for VS70N with console ICE package. 
3. prepare pega and approve.  
4. hold SWB implementation until approval is received from HJG.

@dlabott

**Comment by dlabott** [comment]
@svaughn3 
DGL completed Task 1- Send via email.

**Comment by svaughn3** [comment]
@dlabott 
Sending the change spreadsheets via email. 

Action now is to implement PEGA once H45591RF (Carto IF) is activated and in PCM. 
H45591RF is also holding up the activation of the VS70N with ICE packages:  H45591YZ and H45591ZA. 
These will need to be activated once H45591RF is activated and in PCM. 

Changing to Action: Denise

**Comment by dlabott** [comment]
@svaughn3 
Changing to Make Center PCM action.
Pending catalog activation 45591RF (Carto IF) and activation in rev 6 PCMs

**Comment by svaughn3** [comment]
@dlabott 
Descriptions submitted for approval. 
DOC2111563

**Comment by dlabott** [comment]
@svaughn3 
ACTION: Steve OCR-404 pending review
Descriptions approved DOC2111563
H45591RF not in PCM VIVID-S-V202CHPCM yet 
ACTION: Steve sent email to H-J to confirm status of Carto.

**Comment by svaughn3** [comment]
@dlabott 
April 4 2018

uploaded spreadsheets to OCR-404. 
Ready to go from my standpoint. 
PCM rev 6 is in create state. Rev 6 has H45591RF and h45591AR on it. 

Should be soon!
Can you do everything you can at this point to make move to SWB quick when PCM and H45591RF ready? 

thanks
Steve

**Comment by svaughn3** [comment]
@dlabott 

Steve: work with Mariann to get power cord into the OFCs: H45591YZ and H45591ZA. 
PopUp for the OFCs would need to be revised if power cord goes into OFCs. 

Denise: prepare PEGA (404)  submission but hold on submitting until rev 6 PCM released.

**Comment by svaughn3** [comment]
@dlabott 
April 8, 2018
email sent to Mariann asking for her to make the change to the OFCs.

**Comment by svaughn3** [comment]
@dlabott 
april 12
OFCs 91YZ and 91ZA have the power cord now , but PC is "candidate". 
OFC for Carto and cord: H45591ZK workflow 178499680 
Sending message to Mariann and Joanna and scheduling tcon. 
additional subject: messages between Joanna and Denise concerning approval for DVU and DVO approval for above workflow. 

Steve updating OCR spreads to incorporate Denise's updates and OFC/Popup considerations.

**Comment by svaughn3** [comment]
@dlabott 
May17, 2018
Hold is lifted. 
proceed to SWB with ICE. 
after the new content is in SWB, check content of H45591YZ and H45591ZA, I think they both contain H455901AR Power cord and they shouldn't have to have that now, as power cord is included in H45591ZK, will probably require a revision of OFCs YZ and ZA.

**Comment by svaughn3** [comment]
@dlabott 
May 21, 2018
Resending the "hold is lifted" message: 
Hold is lifted.
 proceed to SWB with ICE.
 after the new content is in SWB, check content of H45591YZ and H45591ZA, I think they both contain H455901AR Power cord and they shouldn't have to have that now, as power cord is included in H45591ZK, will probably require a revision of OFCs YZ and ZA.

**Comment by svaughn3** [comment]
@dlabott 
May 21, 2018
No change to H45591YZ and ZA required because Carto is at FG level, not OFC level and power cord is required in YZ and ZA.

**Comment by dlabott** [comment]
@svaughn3 
May 22, 2018
Need to activate H45591YZ and ZA. Can't find activation workflow.
Denise to add back into offerings once active.

**Comment by svaughn3** [comment]
@dlabott 
June 14, 2018
Steve checked all VS70N and VS70N for USA and all OK - ready to close this item. 

ICECord with Rule - OK
ICE IF - OK
Carto  with Rule - OK
