### ISSUE TITLE
Move EchoPAC Suite offerings into CVUS

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#7]
@dlabott 

Move into Cardiovascular

EchoPAC Suite for ViewPoint v202 
EchoPAC Suite for ViewPoint v202 upgrad 
EchoPAC Suite for ViewPoint Pro v202 
EchoPAC Suite for ViewPoint Pro v202 up 

Action Denise

**Comment by dlabott** [comment]
@svaughn3 
Done! Should appear in SWB by Monday if the overnight production pushes process as expected.

EchoPAC Suite for ViewPoint v202 1013044
EchoPAC Suite for ViewPoint v202 upgrad 1013043
EchoPAC Suite for ViewPoint Pro v202 1013045
EchoPAC Suite for ViewPoint Pro v202 up 1013058

Let me know if you want the order changed.
![image](https://user-images.githubusercontent.com/33458836/32623556-350acb0e-c54c-11e7-97a7-aa77c3273406.png)
