### ISSUE TITLE
Add EP PI to SWB 

### ISSUE THREAD

**Issue by svaughn3** [svaughn3/v202-Maintenance-Issues#8]

**Comment by svaughn3** [comment]
@dlabott 

applicable to upgrades. 
OFC PDT file by Steve on 11/8. 
3 OFC being created: 
FUJI
Siemens
Digisonics

2. These upgrades should go into the EchoPAC Plug In v202 Upgrades (priority #18 from PSI file) I can't find that offering in SWB - does that make sense?

**Comment by dlabott** [comment]
@svaughn3 
Model ECHOPAC PLUG IN V202 UPGRADES is in validation. Emails sent regarding confirmation/clarification of rules. we can discuss during op mech today.

**Comment by svaughn3** [comment]
From: Gorecki-Labott, Denise (GE Healthcare) 
Sent: Tuesday, July 18, 2017 11:11 AM
To: Vaughn, Steven (GE Healthcare) <Steven.Vaughn@ge.com>
Subject: Priority #19 EchoPAC Plug In V202 SWB_CPQ_7154 - Please confirm rules in yellow 

Steve,

Going thru ALL of the offerings to make sure rules / pop ups are set.

Can you please confirm the rules highlighted in yellow below are correct?

I attached my working spreadsheet.
Feel free to edit.



From: Gorecki-Labott, Denise (GE Healthcare) 
Sent: Tuesday, May 23, 2017 1:21 PM
To: Vaughn, Steven (GE Healthcare) <Steven.Vaughn@ge.com>
Cc: Ebben, Brad (GE Healthcare) <Brad.Ebben@ge.com>; Cirillo, Angela M (GE Healthcare) <Angela.Cirillo@ge.com>
Subject: RE: Priority #18 EchoPAC Plug In v202 Upgrades OCR-206 CPQ_7153

Priority #18 EchoPAC Plug In v202 Upgrades  OCR-206  CPQ_7153

Steve
Please confirm when you completed RMM assessment and approved OCR-206.

**Comment by svaughn3** [comment]
@dlabott 

Steve action: 
1. review #18 (OCR-206) and #19 (OCR-207) inputs to Denise. 
2. answer Denise question about rules. 
3. verify all good to go. 
4. Submit inputs to Denise for PEGA

**Comment by svaughn3** [comment]
@dlabott 

I have reviewed the PCL submission files for OCR-206 and OCR-207. 
I have emailed revised files to Denise. 

Changes noted here and in email: 
OCR-207: 
1. see green cells
2. changed 4 rules
3. removed H45601AH

OCR-206: 
1. see green cells
2. Removed H45601BD, H45601WR
3. Added H45601BL, H45601DA
4. Revised 4 rules.

**Comment by dlabott** [comment]
@svaughn3 
Will wait until SWB freeze ends in January 2018

**Comment by dlabott** [comment]
@svaughn3 
I updated the Pegas with notes and updated spreadsheets as indicated here.
Action Denise - update SWB on 2 January 2018

OCR-207
RMM updates - spreadsheet attached 20 Dec 2017
changed 4 rules
removed H45601AH

OCR-206
RMM updates - spreadsheet attached 20 Dec 2017
Removed H45601BD, H45601WR
Added H45601BL, H45601DA --> traced to PCM ECHOPAC-V202PCM rev 5
Revised 4 rules.

**Comment by dlabott** [comment]
@svaughn3 
SWB_CPQ_7154
EchoPAC Plug In V202
OCR-207
RMM updates - spreadsheet attached 20 Dec 2017
changed 4 rules
removed H45601AH

SWB_CPQ_7153	
EchoPAC Plug In v202 Upgrades
OCR-206
RMM updates - spreadsheet attached 20 Dec 2017
Removed H45601BD, H45601WR
Added H45601BL, H45601DA – confirmed PCM rev 5
Revised 4 rules.

Changes made in SWB 2 Jan 2018 (after freeze)

DOC2082750 for description approvals.
Steve confirmed Denise can add to NPI.
Denise will add to CVUS selling domain AFTER approved descriptions are added to SWB.

**Comment by svaughn3** [comment]
@dlabott 
OFCs for EPPC by vendor names (Fuji, Siemens etc.) which triggered regulatory pushback on description approvals.

Pending: Need to document V&V in MWS with an email from each of the 3rd parties.
Glenn Lie to work with the make center to add Supporting documentation/Specification to the HCATs for V&V.

**Comment by svaughn3** [comment]
@dlabott 
moving forward with adding generic EP PI - see email to Denise. 
Descriptions are in for approval. 

OCR: 
OCR_207 CPQ_7154 EP PI v202
OCR-206 CPQ_7153 EP PI v202 Upgrades
spreadsheets are in the email.

**Comment by svaughn3** [comment]
@
Generic EP PI OCR is: 

Copy of OCR-490_CPQ_7153_EchoPAC Plug In v202 Upgrades_6Mar2018
Copy of OCR-490_CPQ_7154_EchoPAC Plug In V202_6Mar2018

descriptions are approved. 
Denise should be able to move forward with PEGA and SWB.

**Comment by svaughn3** [comment]
@dlabott 
April 16, 2018

Offering changes implemented. 7153 and 7154
Denise adding descriptions today and will close when the offering shows in SWB. 
Steve to send note to Denise on where these offerings should show in SWB. 
Should show in SWB on Wednesday.

**Comment by dlabott** [comment]
@svaughn3 
DONE - Denise adding descriptions today and will close when the offering shows in SWB.
ACTION: Steve to send note to Denise on where these offerings should show in SWB.
Should show in SWB on Wednesday.

**Comment by dlabott** [comment]
Confirmed in SWB.
Closing this action.

**Comment by dlabott** [comment]
@svaughn3 
Confirmed in SWB.
Closing this action.
